language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install codacy-coverage
script: make test
after_success:
    - codecov
    - python-codacy-coverage -r coverage.xml
